// ClawEh - Cognitive Memory
// License: MIT
//
// Copyright (c) 2026 Tenebris Technologies Inc.

package cogmem

import (
	"context"
	"fmt"
	"strings"

	"github.com/PivotLLM/ClawEh/pkg/cogmem/store"
)

// renderFullExport renders the agent's entire active cognitive memory as one
// Markdown document: the always-on general domain, every topic domain (with its
// state, triggers, and memories), and the pending-confirmation digest. It returns
// the document plus the domain and memory counts for the tool's summary line.
func renderFullExport(ctx context.Context, s *store.Store) (doc string, nDomains, nMemories int, err error) {
	db := s.DB()
	domains, err := s.ListDomains(ctx, db, store.StatusActive)
	if err != nil {
		return "", 0, 0, err
	}

	var general, projects, workflows, other []store.Domain
	for _, d := range domains {
		switch d.Type {
		case store.DomainGeneral:
			general = append(general, d)
		case store.DomainProject:
			projects = append(projects, d)
		case store.DomainWorkflow:
			workflows = append(workflows, d)
		default:
			other = append(other, d)
		}
	}

	var b strings.Builder
	b.WriteString("# Cognitive Memory Export\n\n")
	b.WriteString("<!-- Snapshot of active memory generated by ClawEh. -->\n\n")

	section := func(title string, ds []store.Domain) error {
		if len(ds) == 0 {
			return nil
		}
		fmt.Fprintf(&b, "## %s\n\n", title)
		for _, d := range ds {
			mems, err := s.ListMemories(ctx, db, d.ID, store.StatusActive)
			if err != nil {
				return err
			}
			nDomains++
			nMemories += len(mems)
			fmt.Fprintf(&b, "### %s · `%s` (%s)\n\n", d.Name, d.ID, d.Type)
			if sm := strings.TrimSpace(d.Summary); sm != "" {
				fmt.Fprintf(&b, "%s\n\n", sm)
			}
			writeList(&b, "Blockers", d.State.Blockers)
			writeList(&b, "Next actions", d.State.NextActions)
			writeList(&b, "Constraints", d.State.Constraints)
			if d.Triggers != "" {
				fmt.Fprintf(&b, "Triggers (auto-load on tool use): `%s`\n\n", d.Triggers)
			}
			if len(mems) == 0 {
				b.WriteString("_(no memories)_\n\n")
				continue
			}
			for _, m := range mems {
				fmt.Fprintf(&b, "- (%s) %s\n", m.Type, strings.TrimSpace(m.Text))
			}
			b.WriteString("\n")
		}
		return nil
	}

	if err := section("General (always in context)", general); err != nil {
		return "", 0, 0, err
	}
	if err := section("Projects", projects); err != nil {
		return "", 0, 0, err
	}
	if err := section("Workflows", workflows); err != nil {
		return "", 0, 0, err
	}
	if err := section("Other", other); err != nil {
		return "", 0, 0, err
	}

	// Pending confirmation digest.
	pending, err := s.ListPending(ctx, db, 0)
	if err != nil {
		return "", 0, 0, err
	}
	if len(pending) > 0 {
		b.WriteString("## Pending Confirmation\n\n")
		b.WriteString("Inferred from conversation, awaiting confirmation (not yet acted on as rules).\n\n")
		for _, m := range pending {
			fmt.Fprintf(&b, "- (%s, confidence %.2f) %s\n", m.Type, m.Confidence, strings.TrimSpace(m.Text))
		}
		b.WriteString("\n")
	}

	return strings.TrimRight(b.String(), "\n") + "\n", nDomains, nMemories, nil
}

func writeList(b *strings.Builder, label string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "%s:\n", label)
	for _, x := range items {
		fmt.Fprintf(b, "- %s\n", x)
	}
	b.WriteString("\n")
}
