import { IconFileTypePdf } from "@tabler/icons-react"

import { PageHeader } from "@/components/page-header"
import { Button } from "@/components/ui/button"

// The report is a PDF generated by the gateway from its loaded configuration;
// the page only explains what it contains and opens it in a new tab, where the
// browser renders it.
const sections = [
  "Identity: product, version, build, host, and the user and group it runs as",
  "Summary: what Claw can access, in one table",
  "Network: every listener and its allowlist",
  "Providers and models: API providers with their models, and CLI providers with the exact command line they are launched with",
  "Credentials and tokens: what is set, never the values",
  "Channels: each messaging channel, who may talk to it, and which agents answer",
  "Agents: tools, MCP access, and every folder each agent can read or write",
  "External services: MCP servers, skills, web search",
  "Devices, data at rest, and scheduled activity",
]

export function AuditPage() {
  return (
    <div className="flex h-full flex-col">
      <PageHeader title="Audit">
        <Button asChild>
          <a href="/api/audit/pdf" target="_blank" rel="noopener">
            <IconFileTypePdf className="size-4" />
            Open audit report (PDF)
          </a>
        </Button>
      </PageHeader>
      <div className="max-w-3xl space-y-4 px-6 pb-6">
        <p className="text-muted-foreground text-sm">
          The audit report describes what this ClawEh instance is able to do:
          what it listens on, which models it talks to, which folders each agent
          can reach, and which external services it can call. It is built from
          the configuration as loaded and from the running process, so it
          reflects this install, not a template. Nothing in it is a secret
          value: keys and tokens appear only as set or not set.
        </p>
        <div className="space-y-1.5">
          <p className="text-foreground text-sm font-semibold">
            What the report contains
          </p>
          <ul className="text-muted-foreground list-disc space-y-1 pl-5 text-sm">
            {sections.map((s) => (
              <li key={s}>{s}</li>
            ))}
          </ul>
        </div>
        <p className="text-muted-foreground text-sm">
          The report opens in a new tab. Generate a fresh one after changing the
          configuration; the header shows when it was produced.
        </p>
      </div>
    </div>
  )
}
