// ClawEh - Cognitive Memory
// License: MIT

package consolidate

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/PivotLLM/ClawEh/pkg/cogmem/store"
)

const exportBanner = "<!-- DO NOT EDIT — autogenerated by ClawEh cognitive memory. Changes will be overwritten. -->\n\n"

// WriteExport renders read-only Markdown projections of the current memory into
// memoryDir, one file per concern. The files mirror what the model sees and let
// a human review learned memory in a text editor; they are never read back.
//
// Best-effort: an empty section is skipped, and a single file's failure does not
// abort the others.
func WriteExport(ctx context.Context, st *store.Store, memoryDir string) error {
	if err := os.MkdirAll(memoryDir, 0o755); err != nil {
		return fmt.Errorf("consolidate: export dir: %w", err)
	}

	domains, err := st.ListDomains(ctx, st.DB(), store.StatusActive)
	if err != nil {
		return fmt.Errorf("consolidate: export list domains: %w", err)
	}

	// Bucket domains: sticky (always in context) vs the rest (topics).
	var sticky, topics []store.Domain
	for _, d := range domains {
		if d.Sticky() {
			sticky = append(sticky, d)
		} else {
			topics = append(topics, d)
		}
	}

	files := map[string]string{
		"GENERATED_STICKY.md":  renderDomains(ctx, st, "Sticky (always in context)", sticky),
		"GENERATED_TOPICS.md":  renderDomains(ctx, st, "Topics", topics),
		"GENERATED_PENDING.md": renderPending(ctx, st),
	}

	var firstErr error
	for name, body := range files {
		if strings.TrimSpace(body) == "" {
			continue
		}
		path := filepath.Join(memoryDir, name)
		if err := os.WriteFile(path, []byte(exportBanner+body), 0o644); err != nil && firstErr == nil {
			firstErr = fmt.Errorf("consolidate: write %s: %w", name, err)
		}
	}
	return firstErr
}

func renderDomains(ctx context.Context, st *store.Store, title string, domains []store.Domain) string {
	if len(domains) == 0 {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", title)
	for _, d := range domains {
		fmt.Fprintf(&b, "## %s\n\n", d.Name)
		if s := strings.TrimSpace(d.Summary); s != "" {
			fmt.Fprintf(&b, "%s\n\n", s)
		}
		hooks, err := st.ListMemories(ctx, st.DB(), d.ID, store.StatusActive)
		if err != nil {
			continue
		}
		for _, h := range hooks {
			fmt.Fprintf(&b, "- (%s · %s) %s\n", h.Type, h.Origin, strings.TrimSpace(h.Text))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderPending(ctx context.Context, st *store.Store) string {
	pending, err := st.ListPending(ctx, st.DB(), 0)
	if err != nil || len(pending) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Pending Confirmation\n\n")
	b.WriteString("Items inferred from conversation, awaiting your confirmation.\n\n")
	for _, h := range pending {
		fmt.Fprintf(&b, "- (%s, confidence %.2f) %s\n", h.Type, h.Confidence, strings.TrimSpace(h.Text))
	}
	return b.String()
}
