import { IconAlertTriangle, IconFileTypePdf } from "@tabler/icons-react"
import { useQuery } from "@tanstack/react-query"
import { useTranslation } from "react-i18next"

import { type ReportAssessment, getReportAssessment } from "@/api/report"
import { PageHeader } from "@/components/page-header"
import { Button } from "@/components/ui/button"

// The full report is a PDF generated by the gateway from its loaded
// configuration. This page shows the part a reviewer reads first — who is
// running what, and the security assessment table — and offers the PDF below.

/** One line: "ClawEh 0.6.0+abc [2026…] · build 2026-09-07T02:00:00Z · linux/amd64 on host". */
function identityLine(
  id: ReportAssessment["identity"],
  buildLabel: string,
): string {
  const parts = [`${id.name} ${id.version}`]
  if (id.build) parts.push(`${buildLabel} ${id.build}`)
  parts.push(id.platform)
  return parts.join(" · ")
}

export function ReportPage() {
  const { t } = useTranslation()
  const { data, isLoading, isError } = useQuery<ReportAssessment>({
    queryKey: ["report-assessment"],
    queryFn: getReportAssessment,
  })

  return (
    <div className="flex h-full flex-col">
      <PageHeader title={t("pages.report.title")} />
      <div className="flex-1 overflow-auto px-4 pb-6 sm:px-6">
        {isLoading ? (
          <div className="text-muted-foreground text-sm">
            {t("labels.loading")}
          </div>
        ) : isError || !data ? (
          <div className="text-destructive text-sm">
            {t("pages.report.load_error")}
          </div>
        ) : (
          <div className="max-w-5xl space-y-4">
            <p
              data-testid="report-identity"
              className="text-muted-foreground font-mono text-xs break-words"
            >
              {identityLine(data.identity, t("pages.report.build"))}
            </p>
            <p className="text-muted-foreground text-sm">
              {t("pages.report.legend")}
            </p>
            <table
              data-testid="report-table"
              className="border-border/40 w-full table-fixed border-t text-sm"
            >
              <thead>
                <tr className="border-border/40 border-b">
                  <th
                    scope="col"
                    className="text-muted-foreground w-10 px-2 py-2.5 text-left text-xs font-medium sm:w-16"
                  >
                    {t("pages.report.col.action")}
                  </th>
                  <th
                    scope="col"
                    className="text-muted-foreground w-1/3 px-2 py-2.5 text-left text-xs font-medium sm:w-1/4"
                  >
                    {t("pages.report.col.item")}
                  </th>
                  <th
                    scope="col"
                    className="text-muted-foreground px-2 py-2.5 text-left text-xs font-medium"
                  >
                    {t("pages.report.col.status")}
                  </th>
                </tr>
              </thead>
              <tbody>
                {data.assessment.map((row, i) => (
                  <tr
                    key={`${i}-${row.item}`}
                    data-testid="report-row"
                    data-action={row.action ? "true" : undefined}
                    className={`border-border/30 border-b align-top last:border-0 ${row.action ? "bg-amber-500/10" : ""}`}
                  >
                    <td className="px-2 py-2.5">
                      {row.action ? (
                        <IconAlertTriangle
                          className="size-4 text-amber-600 dark:text-amber-400"
                          aria-label={t("pages.report.action_needed")}
                          title={t("pages.report.action_needed")}
                        />
                      ) : (
                        <span className="sr-only">
                          {t("pages.report.no_action")}
                        </span>
                      )}
                    </td>
                    <td
                      className={`px-2 py-2.5 break-words ${row.action ? "text-foreground font-medium" : ""}`}
                    >
                      {row.item}
                    </td>
                    <td className="text-muted-foreground px-2 py-2.5 break-words whitespace-normal">
                      {row.status}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="space-y-2 pt-2">
              <Button asChild>
                <a
                  href="/api/report/pdf"
                  target="_blank"
                  rel="noopener"
                  data-testid="report-download"
                >
                  <IconFileTypePdf className="size-4" />
                  {t("pages.report.download")}
                </a>
              </Button>
              <p className="text-muted-foreground text-xs">
                {t("pages.report.download_hint")}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
